version: '3.9'
services:
  app:
    container_name: clean-node-api
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: clean-node-api-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234